### ISSUE TITLE
之前能爬成功,但是后来几次就直接跳转到登录界面了

### ISSUE THREAD

**Issue by CoolerMe** [Python3WebSpider/TaobaoProduct#1]
从搜索界面被重定向到登录界面
https://login.taobao.com/member/login.jhtml?redirectURL=http://s.taobao.com/search?q=iphone
请问是需要做什么处理才能避免这种情况呢?

**Comment by aesdhj** [comment]
我也在看这本书，为这本书建了一个QQ群805370297，方便大家讨论

**Comment by Germey** [comment]
为了避免这种情况，可以先手动登录一遍，然后再再开始爬

**Comment by falconwy** [comment]
老师好，我也遇到了在搜索界面被重定向到登陆界面的问题。
请问 您指的手动登陆，是在driver里模拟登陆，还是指在也浏览器里登陆呢？
令，我发现现在淘宝里的商品页面的request header里 都是provisional headers are shown了，看不到cookie，此时该怎么办呀
