### ISSUE TITLE
整合了下代码，实现了自动登陆，并将图片保存到本地

### ISSUE THREAD

**Issue by Null-Bot9875** [Python3WebSpider/TaobaoProduct#11]
[https://github.com/IlIlIlllIIl/TaobaoProduct](https://github.com/IlIlIlllIIl/TaobaoProduct)

**Comment by chenshipeng** [comment]
需要关闭微博的登录保护，不然会提示要扫码

**Comment by damonpkuml** [comment]
请问如何关闭微博的登录保护呢，谢谢

> 需要关闭微博的登录保护，不然会提示要扫码

**Comment by HIT-Owen** [comment]
手动登录没问题, 自动登录直接弹出字符验证码
