### ISSUE TITLE
如何通过浏览器开发者选项找到所需信息的标签？

### ISSUE THREAD

**Issue by Hostage2018** [Python3WebSpider/TaobaoProduct#12]
shop，location，deal都是和书上一样定位条件，但image，price，title三个信息的定位条件不一致。自己写的定位条件如下：

-  'image': item.find('.J_ItemPic').attr('data-src'),

-  'price': item.find('.price strong').text()

-  'title': item.find('.baoyou').text()

求大佬们指点下如何准确快速找到所需信息的标签

**Comment by Null-Bot9875** [comment]
用xpath或者css选择器

**Comment by Germey** [comment]
chrome 的调试工具，elements，然后 ctrl + F
