### ISSUE TITLE
已经扫码登陆成功，但是在爬取10页之后，淘宝会跳出 滑块访问验证

### ISSUE THREAD

**Issue by BrambleXu** [Python3WebSpider/TaobaoProduct#13]
已经扫码登陆成功，但是在爬取10页之后，淘宝会跳出 滑块访问验证。请问有遇到这个问题的小伙伴是如何解决的。

![image](https://user-images.githubusercontent.com/10768193/66479573-c675fc00-ead7-11e9-850c-77edf98f2486.png)

我在selenium打开的页面里拖动了滑块，但是没有效果，显示验证失败。

![image](https://user-images.githubusercontent.com/10768193/66480376-80219c80-ead9-11e9-8cfd-de2b74b3536c.png)

有没有可以绕过滑块检测的方法，比如每爬取1页就休息5s。尽量不触发淘宝的反爬虫机制

**Comment by Germey** [comment]
https://mp.weixin.qq.com/s/Iz-DY1UrSfVFRFh5CyHl3Q 参考这个
