### ISSUE TITLE
新版本的selenium不支持Phantomjs了

### ISSUE THREAD

**Issue by untamedtao** [Python3WebSpider/TaobaoProduct#14]
淘宝的反爬虫机制也改了，现在用selenium只能爬第一页，翻页的时候会被检测出来，禁止操作

**Comment by DonkeyL** [comment]
唉

**Comment by XHXJ** [comment]
我这边是登陆的时候滑动条一直无法完成检测屏蔽selenium有关

**Comment by untamedtao** [comment]
> 我这边是登陆的时候滑动条一直无法完成检测屏蔽selenium有关

建议从微博登录入口进

**Comment by Germey** [comment]
登录的问题见：https://github.com/Python3WebSpider/TaobaoProduct/issues/15

PhantomJS 可以把 Selenium 降低版本，如 3.4

**Comment by hannzhao** [comment]
微博登陆几乎都要输入验证码了
