### ISSUE TITLE
无需登陆的其他尝试，页码输入框的页码值已经改为value属性的值，需要模拟JavaScript修改。

### ISSUE THREAD

**Issue by james-wangx** [Python3WebSpider/TaobaoProduct#20]
### 方式1：控制已经打开的浏览器
打开cmd，输入**chrome.exe --remote-debugging-port=9222 --user-data-dir="C:\selenum\AutomationProfile"**
作用是打开Chrome，指定远程调试端口，设置一个新的配置目录，不影响源目录

使用这个新开的浏览器访问淘宝，登陆后搜索商品
然后运行以下代码（chromedriver放在/Python/Script目录下）
```
from selenium.webdriver.chrome.options import Options
from selenium import webdriver

# 初始化浏览器选项对象
chrome_options = Options()
# 添加拓展选项，指定调试端口
chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
# driver = webdriver.Chrome(chrome_options=chrome_options)
# selenium3.141.0   python3.8.1出现弃用警告
# DeprecationWarning: use options instead of chrome_options
# 将chrome_options换成option
driver = webdriver.Chrome(options=chrome_options)
print(driver.title)
```

### 方式2：加载所有Chrome配置
提前访问淘宝，登陆并搜索商品，让浏览器保存相关信息
```
from selenium import webdriver
option = webdriver.ChromeOptions()
p=r'C:\Users\Administrator\AppData\Local\Google\Chrome\User Data'
option.add_argument('--user-data-dir='+p)  # 设置成用户自己的数据目录
driver = webdriver.Chrome(chrome_options=option)
```

### 页码输入框的页码值已经改为value属性的值，需要模拟JavaScript修改。
```
        if page > 1:
            input = wait.until(
                EC.presence_of_element_located((By.CLASS_NAME, 'J_Input'))
            )
            submit = wait.until(
                EC.element_to_be_clickable((By.CLASS_NAME, 'J_Submit'))
            )
            # 模拟JavaScript修改结点的属性值
            browser.execute_script("arguments[0].setAttribute('value','{}');".format(str(page)), input)
            submit.click()
```

**Comment by Germey** [comment]
感谢建议，我后面找时间修改一下

**Comment by james-wangx** [comment]
这几天都在看崔老师的书，受益颇深，感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "崔庆才丨静觅"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 中午11:11
收件人: "Python3WebSpider/TaobaoProduct"<TaobaoProduct@noreply.github.com&gt;; 
抄送: "王舰"<cppjavapython@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Python3WebSpider/TaobaoProduct] 无需登陆的其他尝试，页码输入框的页码值已经改为value属性的值，需要模拟JavaScript修改。 (#20)





 
感谢建议，我后面找时间修改一下

**Comment by evilchaos** [comment]
> ### 方式1：控制已经打开的浏览器
> 打开cmd，输入**chrome.exe --remote-debugging-port=9222 --user-data-dir="C:\selenum\AutomationProfile"**
> 作用是打开Chrome，指定远程调试端口，设置一个新的配置目录，不影响源目录
> 
> 使用这个新开的浏览器访问淘宝，登陆后搜索商品
> 然后运行以下代码（chromedriver放在/Python/Script目录下）
> 
> ```
> from selenium.webdriver.chrome.options import Options
> from selenium import webdriver
> 
> # 初始化浏览器选项对象
> chrome_options = Options()
> # 添加拓展选项，指定调试端口
> chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
> # driver = webdriver.Chrome(chrome_options=chrome_options)
> # selenium3.141.0   python3.8.1出现弃用警告
> # DeprecationWarning: use options instead of chrome_options
> # 将chrome_options换成option
> driver = webdriver.Chrome(options=chrome_options)
> print(driver.title)
> ```
> 
> ### 方式2：加载所有Chrome配置
> 提前访问淘宝，登陆并搜索商品，让浏览器保存相关信息
> 
> ```
> from selenium import webdriver
> option = webdriver.ChromeOptions()
> p=r'C:\Users\Administrator\AppData\Local\Google\Chrome\User Data'
> option.add_argument('--user-data-dir='+p)  # 设置成用户自己的数据目录
> driver = webdriver.Chrome(chrome_options=option)
> ```
> 
> ### 页码输入框的页码值已经改为value属性的值，需要模拟JavaScript修改。
> ```
>         if page > 1:
>             input = wait.until(
>                 EC.presence_of_element_located((By.CLASS_NAME, 'J_Input'))
>             )
>             submit = wait.until(
>                 EC.element_to_be_clickable((By.CLASS_NAME, 'J_Submit'))
>             )
>             # 模拟JavaScript修改结点的属性值
>             browser.execute_script("arguments[0].setAttribute('value','{}');".format(str(page)), input)
>             submit.click()
> ```

第一种方式已经失效了，滑块始终验证不通过。

**Comment by Pineapple666** [comment]
对没错，之前我还试过模仿拖动滑块成功的，后来也坏了，怎么都滑不了，连手动也不行。
利用微博登录是个好主意，但我最近老跳出来手机验证。
后来又尝试了post请求，这个管用。

**Comment by james-wangx** [comment]
@evilchaos 
对没错，之前我还试过模仿拖动滑块成功的，后来也坏了，怎么都滑不了，连手动也不行。
利用微博登录是个好主意，但我最近老跳出来手机验证。
后来又尝试了post请求，这个管用。
