### ISSUE TITLE
关于一直在正在爬取第 1 页

### ISSUE THREAD

**Issue by yzw1** [Python3WebSpider/TaobaoProduct#3]
也不报错，爬了很长时间还是    正在爬取第 1 页   因为我只想把数据打印出来，所以把数据库的存储方法注释掉了

**Comment by xiaaoo-zz** [comment]
请问现在爬需要登陆了怎么破

**Comment by ghost** [comment]
爬不了，TimeoutException

**Comment by xiezhedaima9591** [comment]
你们把那个headless那个选项去掉，让它把界面显示出来，你就明白了，它一开始会让你登陆，后面找页面元素的部分就会报异常，然后就会重新跑一遍，就会陷入循环，目测需要把登陆后的cookie用add_cookies方法加到browser上，应该就可以了，还没试。

**Comment by xiezhedaima9591** [comment]
额，我看了一下别人怎么解决的，就简单粗暴的出来登陆页面后，用手机淘宝扫一下。。。。是可以的
