### ISSUE TITLE
总是显示一直在爬第1页，停不下来。什么问题？

### ISSUE THREAD

**Issue by studypythonnew** [Python3WebSpider/TaobaoProduct#4]
总是显示一直正在爬第1页，停不下来。什么问题？

**Comment by xiezhedaima9591** [comment]
你把那个headless那个选项去掉，让它把界面显示出来，你就明白了，它一开始会让你登陆，后面找页面元素的部分就会报异常，然后就会重新跑一遍，就会陷入循环

**Comment by xiezhedaima9591** [comment]
额，我看了一下别人怎么解决的，就简单粗暴的出来登陆页面后，用手机淘宝扫一下。。。。是可以的

**Comment by wangzhihaiSF** [comment]
![2](https://user-images.githubusercontent.com/15885797/51099010-faeaaf00-1808-11e9-94db-93e01029e72b.PNG)

**Comment by wangzhihaiSF** [comment]
抓取过程中，淘宝让活动模块。，。

**Comment by studypythonnew** [comment]
多谢回头试试

Charles <notifications@github.com>于2019年1月10日 周四下午3:20写道：
