### ISSUE TITLE
为啥我这个淘宝网上没显示那个xhr文件

### ISSUE THREAD

**Issue by yongyixiao** [Python3WebSpider/TaobaoProduct#5]
![image](https://user-images.githubusercontent.com/33975438/51421617-94d0a400-1bdb-11e9-9383-539bafbc2289.png)

**Comment by wardseptember** [comment]
刷新页面

**Comment by existenceE** [comment]
> 刷新页面

刷新页面还是不行，我这边也是没有XHR

**Comment by SeanTong11** [comment]
第一次有的,后面进就没了

**Comment by mooncakedevop** [comment]
我这边也是没有xhr
