### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by ixzzVing** [Python3WebSpider/TaobaoProduct#8]
from config import *
ModuleNotFoundError: No module named 'config'

这个是哪个库没安装好吗？

**Comment by Nobodylesszb** [comment]
这个你没config文件

**Comment by jojoasd123** [comment]
我也出现了这个问题, 我下了一整本书的实例代码.
因为爬淘宝的脚本 在 taobaoproduct文件夹内, 所以出现的.
改一下就好了. 
from taobaoproduct.config import *

**Comment by Nobodylesszb** [comment]
好的，谢谢




发自网易邮箱大师
在2019年06月30日 13:19，jojoasd123 写道：

我也出现了这个问题, 我下了一整本书的实例代码.
因为爬淘宝的脚本 在 taobaoproduct文件夹内, 所以出现的.
改一下就好了.
from taobaoproduct.config import *
